### ISSUE TITLE
Collapsible Sidebar not working in Nova 4

### ISSUE THREAD

**Issue by MicaiasOliveira** [stepanenko3/nova-menu-collapsed#1]
I tried to use the package in my app and it didn't work. After following all the steps, it did not show any bugs, but the collapse did not work. Can you help me?

**Comment by stepanenko3** [comment]
Hi, @MicaiasOliveira 

Fixed in [v1.2.2](https://github.com/stepanenko3/nova-menu-collapsed/releases/tag/v1.2.2)
